#!/bin/sh

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# Colors
bspc config active_border_color     \#d79921
bspc config focused_border_color    \#d79921
bspc config normal_border_color     \#363836

# Rules
bspc rule -a mpv state=floating
bspc rule -a "*:pulsemixer:*" state=floating
bspc rule -a "*:htop:*" state=floating
bspc rule -a "*:quick:*" state=floating
